# ========== Profile ========== #
# avatar
avatar: /avatar/kumamon.jpeg
# author name
author: Toono 
# signature
signature: Are you OK ?
# SNS
social:
  email: toono@qq.com
  github: //github.com/ToonoW
  #weibo:
  # zhihu:
  # facebook:
  twitter: //twitter.com/toono_w
  # instagram:
  # stack-overflow:
  # linkedin:
# friends
# friends:
  # friendA: //www.baidu.com
  # friendB: //www.google.com
  # friendC :

# ========== Site ========== #
# title of the site
SEO_title: 快乐的鲸鱼 
# main title
main_title: 快乐的鲸鱼
# subtitle
subtitle: IT'S BETTER TO BURN OUT THAN TO FADE AWAY.
# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere:
  # isso 支持
  isso:
    data_url: 'http://comment.toonow.cc/'
    src_url: 'http://comment.toonow.cc/js/embed.min.js'

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: false
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /favicon.ico
# truncate length (the default is 300)
truncate_length:


about:
  enable: false
